sudo: required
services: 
  - docker

before_install:
  - docker build -t xalster/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true xalster/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-906495541320"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"